// src/context/LanguageContext.jsx
import React, { createContext, useContext, useState, useCallback } from 'react';

// Translations object
const translations = {
    pt: {
        // Auth Page
        'auth.welcome': 'Bem-vindo de volta!',
        'auth.createAccount': 'Crie sua conta',
        'auth.platformAccess': 'Plataforma ELIS de Integridade Científica',
        'auth.username': 'Username',
        'auth.usernamePlaceholder': 'seu_username',
        'auth.fullName': 'Nome Completo',
        'auth.fullNamePlaceholder': 'João da Silva',
        'auth.usernameOrEmail': 'Username ou Email',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'seu@email.com',
        'auth.password': 'Senha',
        'auth.passwordPlaceholder': '••••••••',
        'auth.login': 'Entrar na Plataforma',
        'auth.register': 'Criar Conta',
        'auth.loading': 'Carregando...',
        'auth.noAccount': 'Não tem uma conta?',
        'auth.hasAccount': 'Já tem uma conta?',
        'auth.signupHere': 'Cadastre-se aqui',
        'auth.loginHere': 'Faça login',
        'auth.copyright': '© 2024 ELIS Platform. Todos os direitos reservados.',

        // Sidebar
        'sidebar.platform': 'Scientific Integrity',
        'sidebar.researcher': 'Pesquisador',
        'sidebar.search': 'Buscar...',
        'sidebar.images': 'Imagens',
        'sidebar.uploadImages': 'Upload Imagens',
        'sidebar.gallery': 'Galeria',
        'sidebar.annotate': 'Anotar Imagens',
        'sidebar.documents': 'Documentos',
        'sidebar.viewPdfs': 'Visualizar PDFs',
        'sidebar.uploadPdf': 'Enviar PDF',
        'sidebar.tools': 'Ferramentas',
        'sidebar.findSimilar': 'Buscar Similares',
        'sidebar.imageAnalysis': 'Análise de Imagem',
        'sidebar.tags': 'Etiquetas',
        'sidebar.categories': 'Categorias',
        'sidebar.settings': 'Configurações',
        'sidebar.general': 'Geral',
        'sidebar.profile': 'Perfil',
        'sidebar.comingSoon': 'Em breve',
        'sidebar.online': 'Online',

        // Topbar
        'topbar.title': 'ELIS Scientific Integrity',
        'topbar.subtitle': 'Ferramentas avançadas para análise de imagens científicas',

        // Common
        'common.loading': 'Carregando...',
        'common.pleaseWait': 'Aguarde um momento...',
        'common.user': 'Usuário',
        'common.logout': 'Sair',
        'common.searchPage': 'Página "Search" (Em breve)',
        'common.cancel': 'Cancelar',
        'common.save': 'Salvar',
        'common.edit': 'Editar',
        'common.delete': 'Excluir',
        'common.confirm': 'Confirmar',
        'common.success': 'Sucesso!',
        'common.error': 'Erro',
        'common.warning': 'Atenção',
        'common.tryAgain': 'Tentar Novamente',
        'common.addMore': 'Adicionar mais',
        'common.filters': 'Filtros',
        'common.active': 'Ativos',
        'common.all': 'Todas',
        'common.origin': 'Origem',
        'common.update': 'Atualizar',
        'common.back': 'Voltar',
        'common.selected': 'selecionadas',

        // Upload Pages
        'upload.title': 'Upload de Imagens',
        'upload.subtitle': 'Adicione imagens para análise e processamento',
        'upload.pdfTitle': 'Upload de PDF',
        'upload.pdfSubtitle': 'Adicione documentos PDF para extração e análise',
        'upload.dragDropImages': 'Arraste e solte suas imagens aqui',
        'upload.dragDropPdfs': 'Arraste e solte seus PDFs aqui',
        'upload.orClick': 'ou clique para selecionar do computador',
        'upload.supportsImages': 'Suporta: JPG, PNG, GIF, WEBP',
        'upload.supportsPdf': 'Suporta: PDF',
        'upload.selectedFiles': 'Arquivos Selecionados',
        'upload.completeUpload': 'Concluir Upload',
        'upload.selectAtLeastOneImage': 'Por favor, selecione pelo menos uma imagem.',
        'upload.selectAtLeastOnePdf': 'Por favor, selecione pelo menos um PDF.',
        'upload.uploadSuccess': 'Upload concluído com sucesso!',
        'upload.uploadPartial': 'Upload concluído parcialmente.',
        'upload.uploadFailed': 'Falha no Upload. Tente novamente.',
        'upload.imagesUploaded': 'imagem(ns) enviada(s) com sucesso!',
        'upload.pdfsUploaded': 'PDF(s) enviado(s) com sucesso!',
        'upload.successCount': 'sucesso(s)',
        'upload.failureCount': 'falha(s)',

        // Gallery
        'gallery.title': 'Galeria',
        'gallery.subtitle': 'Gerencie, organize e analise suas imagens extraídas e enviadas.',
        'gallery.empty': 'Galeria vazia',
        'gallery.noResults': 'Nenhum resultado encontrado',
        'gallery.emptyDescription': 'Comece enviando algumas imagens para análise ou extraindo de PDFs.',
        'gallery.noResultsDescription': 'Tente ajustar seus filtros ou buscar por outros termos.',
        'gallery.upload': 'Fazer Upload',
        'gallery.noTags': 'Sem tags',
        'gallery.uploaded': 'Upload',
        'gallery.extracted': 'Extraída',
        'gallery.searchPlaceholder': 'Buscar imagens...',
        'gallery.sortNewest': 'Mais recentes',
        'gallery.sortOldest': 'Mais antigas',
        'gallery.sortNameAsc': 'Nome (A-Z)',
        'gallery.sortNameDesc': 'Nome (Z-A)',
        'gallery.sortSize': 'Tamanho',
        'gallery.errorLoading': 'Erro ao carregar imagens',
        'gallery.imagesTotal': 'imagens no total',
        'gallery.selectAllImages': 'Selecionar Todas',
        'gallery.selectAllFiltered': 'Selecionar Todos Filtrados',
        'gallery.clearAllSelection': 'Limpar Tudo',
        'gallery.images': 'imagens',
        'gallery.first': 'Primeira',
        'gallery.last': 'Última',
        'gallery.previousPage': 'Página anterior',
        'gallery.nextPage': 'Próxima página',

        // Image Filters Panel
        'filters.title': 'Filtros',
        'filters.origin': 'Origem',
        'filters.originAll': 'Todas',
        'filters.originUploaded': 'Enviadas por Mim',
        'filters.originExtracted': 'Extraídas de PDF',
        'filters.date': 'Data',
        'filters.dateFrom': 'De',
        'filters.dateTo': 'Até',
        'filters.tags': 'Tags',
        'filters.clearFilters': 'Limpar Filtros',
        'filters.noTagsAvailable': 'Nenhuma tag encontrada nas imagens',


        // Lightbox Modal
        'lightbox.tagsClassification': 'Tags & Classificação',
        'lightbox.metadata': 'Metadados',
        'lightbox.origin': 'Origem',
        'lightbox.format': 'Formato',

        // Selection Toolbar
        'selection.selected': 'selecionado',
        'selection.selectedPlural': 'selecionados',
        'selection.clearSelection': 'Limpar seleção',
        'selection.findSimilar': 'Buscar Similares',
        'selection.findSimilarTitle': 'Buscar imagens similares',
        'selection.viewMetadata': 'Metadados',
        'selection.viewMetadataTitle': 'Ver detalhes da imagem',
        'selection.classify': 'Classificar',
        'selection.analyze': 'Analisar',
        'selection.delete': 'Excluir',
        'selection.extractPanels': 'Extrair Painéis',
        'selection.extractPanelsTitle': 'Extrair painéis individuais das imagens selecionadas',
        'selection.extracting': 'Extraindo...',

        // Panel Extraction
        'panelExtraction.started': 'Extração de painéis iniciada',
        'panelExtraction.processing': 'Processando imagens...',
        'panelExtraction.success': 'Extraídos {count} painéis com sucesso',
        'panelExtraction.failed': 'Falha na extração de painéis',
        'panelExtraction.noPanelsFound': 'Nenhum painel encontrado nas imagens selecionadas',
        'panelExtraction.timeout': 'Extração de painéis expirou',
        'panelExtraction.noImagesSelected': 'Nenhuma imagem selecionada para extração',

        // Batch Operations
        'batch.imagesDeleted': 'imagens excluídas com sucesso.',
        'batch.extractedIgnored': 'imagens extraídas foram ignoradas.',
        'batch.tagsAdded': 'tags adicionadas a',
        'batch.images': 'imagens.',
        'batch.analyzeComingSoon': 'Funcionalidade de análise em lote em breve!',
        'batch.actionBlocked': 'Ação Bloqueada',
        'batch.extractedOnlyMessage': 'Você selecionou {count} imagem(ns) extraída(s). Elas só podem ser removidas excluindo o PDF original.',
        'batch.confirmDelete': 'Tem certeza que deseja excluir {count} imagens?',
        'batch.confirmDeleteNote': '(Atenção: {count} imagens extraídas selecionadas serão ignoradas e não serão excluídas)',
        'batch.confirmation': 'Confirmação',

        // Tag Input
        'tags.addTags': 'Adicionar tags...',

        // Image display
        'image.error': 'Erro',
        'image.loadError': 'Erro ao carregar imagem',
        'image.noTags': 'Sem tags',
        'image.uploaded': 'Upload',
        'image.extracted': 'Extraída',
        'image.noName': 'Sem nome',

        // Image operations (useImages hook)
        'images.actionBlocked': 'Ação Bloqueada',
        'images.extractedCannotDelete': 'Imagens extraídas não podem ser excluídas individualmente. Para remover esta imagem, você deve excluir o PDF original na aba "Documentos".',
        'images.confirmDeleteTitle': 'Tem certeza?',
        'images.confirmDeleteMessage': 'Deseja realmente excluir a imagem "{filename}"?',
        'images.deleteSuccess': 'Imagem deletada com sucesso!',
        'images.deleteError': 'Erro ao deletar',
        'images.tagsAddedSuccess': 'Tags adicionadas com sucesso!',
        'images.tagsAddError': 'Erro ao adicionar tags',
        'images.tagRemovedSuccess': 'Tag removida com sucesso.',
        'images.tagRemoveError': 'Erro ao remover tag',

        // Similarity Search
        'similarity.title': 'Busca por Similaridade',
        'similarity.searching': 'Buscando...',
        'similarity.resultsFound': 'resultados encontrados',
        'similarity.topK': 'Top-K',
        'similarity.threshold': 'Limiar',
        'similarity.category': 'Categoria',
        'similarity.selectAllResults': 'Selecionar Todos Resultados',
        'similarity.noResults': 'Nenhuma imagem similar encontrada.',
        'similarity.foundResults': 'imagens similares encontradas!',
        'similarity.found': 'Encontradas',
        'similarity.similarImages': 'imagens similares!',
        'similarity.searchError': 'Erro na busca',
        'similarity.searchErrorMessage': 'Erro ao buscar imagens similares.',
        'similarity.selectOneImage': 'Selecione exatamente uma imagem para buscar similares.',

        // Batch Tag Modal
        'batchTag.title': 'Classificar Imagens',
        'batchTag.description': 'Adicione tags para classificar as',
        'batchTag.selectedImages': 'imagens selecionadas',
        'batchTag.addToExisting': 'Elas serão adicionadas às tags existentes.',
        'batchTag.newTags': 'Novas Tags',
        'batchTag.addTags': 'Adicionar Tags',

        // Profile Page
        'profile.title': 'Meu Perfil',
        'profile.subtitle': 'Gerencie suas informações pessoais e configurações',
        'profile.fullName': 'Nome Completo',
        'profile.fullNamePlaceholder': 'Seu nome completo',
        'profile.email': 'Email',
        'profile.editProfile': 'Editar Perfil',
        'profile.saveChanges': 'Salvar Alterações',
        'profile.saving': 'Salvando...',
        'profile.storage': 'Armazenamento',
        'profile.used': 'usado',
        'profile.total': 'total',
        'profile.spaceUsed': 'do espaço utilizado',
        'profile.accountInfo': 'Informações da Conta',
        'profile.createdAt': 'Criada em',
        'profile.lastUpdate': 'Última atualização',
        'profile.dangerZone': 'Zona de Perigo',
        'profile.dangerDescription': 'A exclusão da conta é permanente e não pode ser desfeita. Todos os seus documentos serão deletados.',
        'profile.deleteAccount': 'Deletar Conta Permanentemente',
        'profile.errorLoading': 'Erro ao carregar perfil',
        'profile.deleteConfirmTitle': 'ATENÇÃO: Esta ação é IRREVERSÍVEL!',
        'profile.deleteConfirmMessage': 'Todos os seus documentos e dados serão PERMANENTEMENTE deletados.',
        'profile.deleteConfirmPrompt': 'Digite seu nome de usuário para confirmar:',
        'profile.deleteCancelled': 'Nome de usuário incorreto. Ação cancelada.',

        // View PDFs Page
        'pdfs.title': 'Meus Documentos',
        'pdfs.subtitle': 'Visualize e gerencie seus documentos PDF',
        'pdfs.empty': 'Nenhum PDF enviado',
        'pdfs.noDocFound': 'Nenhum documento encontrado',
        'pdfs.emptyDescription': 'Você ainda não enviou nenhum documento PDF para a plataforma.',
        'pdfs.searchNoResults': 'Tente buscar com outros termos ou limpe os filtros.',
        'pdfs.uploadNow': 'Fazer Upload Agora',
        'pdfs.documentsFound': 'documentos encontrados',
        'pdfs.searchPlaceholder': 'Buscar documentos...',
        'pdfs.sortNewest': 'Mais recentes',
        'pdfs.sortOldest': 'Mais antigos',
        'pdfs.sortSize': 'Maior tamanho',
        'pdfs.view': 'Visualizar',
        'pdfs.download': 'Baixar',
        'pdfs.delete': 'Excluir',
        'pdfs.watermarkOptions': 'Opções de Marca d\'água',
        'pdfs.removeWatermark': 'Remover Marca d\'Água',
        'pdfs.none': 'Nenhum',
        'pdfs.keepOriginal': 'Manter original',
        'pdfs.level1': 'Nível 1',
        'pdfs.level1Sub': 'Remoção leve',
        'pdfs.level2': 'Nível 2',
        'pdfs.level2Sub': 'Remoção média',
        'pdfs.level3': 'Nível 3',
        'pdfs.level3Sub': 'Remoção agressiva',
        'pdfs.loadingDoc': 'Carregando documento...',
        'pdfs.loadError': 'Não foi possível carregar o documento.',
        'pdfs.complete': 'Completo',
        'pdfs.processing': 'Processando',
        'pdfs.waiting': 'Aguardando',
        'pdfs.grid': 'Grade',
        'pdfs.list': 'Lista',
        'pdfs.splitView': 'Visualização Dividida',
        'pdfs.selectDocToView': 'Selecione um documento para visualizar',
        'pdfs.name': 'Nome',
        'pdfs.date': 'Data',
        'pdfs.size': 'Tamanho',
        'pdfs.status': 'Status',
        'pdfs.actions': 'Ações',
        'pdfs.goToUpload': 'Vá para a página de upload',
        'document.confirmDeleteTitle': 'Tem certeza?',
        'document.confirmDeleteMessage': 'Deseja realmente excluir o documento "{filename}"? Esta ação não pode ser desfeita.',
        'document.deleteSuccess': 'Documento deletado com sucesso!',
        'document.downloadStarted': 'Download iniciado!',
        'document.downloadError': 'Erro ao baixar',
        'document.deleteError': 'Erro ao deletar',
        'document.fetchError': 'Erro ao buscar documentos',

        // CBIR Search Page
        'cbir.title': 'Buscar Imagens Similares',
        'cbir.subtitle': 'Selecione uma imagem de origem e encontre imagens visualmente similares na sua galeria.',
        'cbir.clearSearch': 'Limpar busca',
        'cbir.noImages': 'Nenhuma imagem disponível',
        'cbir.noImagesDescription': 'Faça upload de imagens primeiro para usar a busca por similaridade.',
        'cbir.noSimilarFound': 'Nenhuma imagem similar encontrada',
        'cbir.noSimilarDescription': 'Tente ajustar os parâmetros de busca ou selecionar outra imagem de origem.',
        'cbir.selectSource': 'Selecionar Imagem de Origem',
        'cbir.selectSourceDescription': 'Escolha a imagem que será usada como referência para a busca',
        'cbir.searchParams': 'Parâmetros de Busca',
        'cbir.searchParamsDescription': 'Configure os critérios para refinar sua busca',
        'cbir.topK': 'Número de Resultados (Top-K)',
        'cbir.topKDescription': 'Quantidade máxima de imagens similares a retornar (1-100)',
        'cbir.minSimilarity': 'Similaridade Mínima',
        'cbir.minSimilarityDescription': 'Filtrar resultados abaixo deste limiar de similaridade',
        'cbir.categoryFilter': 'Filtro por Categoria/Tipo',
        'cbir.allTypes': 'Todos os Tipos',
        'cbir.autoSelected': 'Auto-selecionado baseado na imagem de origem',
        'cbir.filterByType': 'Filtrar resultados por tipo de imagem',
        'cbir.selectedImage': 'Imagem selecionada:',
        'cbir.noImageSelected': 'Nenhuma imagem selecionada',
        'cbir.analyze': 'Analisar',
        'cbir.searching': 'Buscando...',
        'cbir.searchResults': 'Resultados da Busca',
        'cbir.imagesFound': 'de',
        'cbir.imagesFoundSuffix': 'imagens encontradas',
        'cbir.filteredBySimilarity': 'filtradas por similaridade mínima',
        'cbir.error': 'Erro',
        'cbir.noTags': 'Sem tags',
        'cbir.similarity': 'Similaridade',
        'cbir.tags': 'Tags',
        'cbir.info': 'Informações',
        'cbir.origin': 'Origem',
        'cbir.selectSourceFirst': 'Selecione uma imagem de origem primeiro.',
        'cbir.noResultsWithCriteria': 'Nenhuma imagem similar encontrada com os critérios atuais.',

        // Annotation Page
        'annotation.title': 'Anotar Imagens',
        'annotation.subtitle': 'Adicione anotações e marcações às suas imagens',
        'annotation.selectImage': 'Selecione uma imagem para anotar',
        'annotation.tools': 'Ferramentas',
        'annotation.rectangle': 'Retângulo',
        'annotation.circle': 'Círculo',
        'annotation.arrow': 'Seta',
        'annotation.text': 'Texto',
        'annotation.saveAnnotation': 'Salvar Anotação',
        'annotation.listTitle': 'Anotações',
        'annotation.placeholder': 'Digite sua anotação aqui...',
        'annotation.noAnnotations': 'Nenhuma anotação.',
        'annotation.type': 'Tipo',
        'annotation.manipulation': 'Manipulação',
        'annotation.copyMove': 'Cópia-Mover',
        'annotation.groupId': 'ID do Grupo',
        'annotation.group': 'Grupo',

        // Image Analysis Page
        'analysis.title': 'Análise de Imagem',
        'analysis.subtitle': 'Ferramentas forenses para verificação de integridade de imagens científicas',
        'analysis.inspiredBy': 'Inspirado por Forensically',
        'analysis.selectImage': 'Selecionar Imagem',
        'analysis.selectImageDesc': 'Escolha uma imagem da sua galeria para analisar',
        'analysis.selectTool': 'Selecionar Ferramenta',
        'analysis.selectToolDesc': 'Escolha uma ferramenta forense para analisar a imagem',
        'analysis.parameters': 'Parâmetros e Execução',
        'analysis.parametersDesc': 'Ajuste as configurações e execute a análise',
        'analysis.selectedImage': 'Imagem selecionada:',
        'analysis.noImageSelected': 'Nenhuma imagem selecionada',
        'analysis.runAnalysis': 'Executar Análise',
        'analysis.analyzing': 'Analisando...',
        'analysis.results': 'Resultados da Análise',
        'analysis.result': 'Resultado',
        'analysis.original': 'Original',
        'analysis.processing': 'Processando...',
        'analysis.complete': 'Análise concluída',
        'analysis.error': 'Erro durante a análise',
        'analysis.selectImageFirst': 'Selecione uma imagem primeiro',
        'analysis.noImages': 'Nenhuma imagem encontrada',
        'analysis.noImagesDesc': 'Faça upload de imagens para começar a análise.',
        'analysis.selectAndRun': 'Selecione uma imagem e execute a análise',
        'analysis.selectDescription': 'Escolha uma imagem da galeria e selecione uma ferramenta para iniciar.',
        'analysis.noParams': 'Sem parâmetros ajustáveis para esta ferramenta.',
        'analysis.fileSize': 'Tamanho do Arquivo',
        'analysis.foundStrings': 'Encontradas',
        'analysis.strings': 'strings',
        'analysis.noStrings': 'Nenhuma string significativa encontrada',
        'analysis.tools.ela': 'Análise de Nível de Erro',
        'analysis.tools.noise': 'Análise de Ruído',
        'analysis.tools.gradient': 'Gradiente de Luminância',
        'analysis.tools.levelSweep': 'Varredura de Níveis',
        'analysis.tools.magnifier': 'Lupa',
        'analysis.tools.cloneDetection': 'Detecção de Clone',
        'analysis.tools.metadata': 'Metadados',
        'analysis.tools.jpegAnalysis': 'Análise JPEG',
        'analysis.tools.strings': 'Extração de Strings',
        'analysis.tools.ela.description': 'Compara a imagem com uma versão recomprimida para detectar manipulação',
        'analysis.tools.noise.description': 'Extrai e visualiza o padrão de ruído da imagem',
        'analysis.tools.gradient.description': 'Visualiza mudanças de brilho para detectar inconsistências de iluminação',
        'analysis.tools.levelSweep.description': 'Destaca níveis específicos de brilho para revelar detalhes ocultos',
        'analysis.tools.magnifier.description': 'Zoom e aprimoramento de detalhes com equalização de histograma',
        'analysis.tools.cloneDetection.description': 'Identifica regiões potencialmente copiadas e coladas',
        'analysis.tools.metadata.description': 'Visualiza propriedades da imagem e informações incorporadas',
        'analysis.tools.jpegAnalysis.description': 'Analisa estrutura JPEG e tabelas de quantização',
        'analysis.tools.strings.description': 'Extrai strings de texto incorporadas no arquivo de imagem',
        'analysis.params.quality': 'Qualidade JPEG',
        'analysis.params.jpegQuality': 'Qualidade JPEG',
        'analysis.params.scale': 'Escala de Erro',
        'analysis.params.errorScale': 'Escala de Erro',
        'analysis.params.amplitude': 'Amplitude do Ruído',
        'analysis.params.noiseAmplitude': 'Amplitude do Ruído',
        'analysis.params.equalize': 'Equalizar Histograma',
        'analysis.params.equalizeHistogram': 'Equalizar Histograma',
        'analysis.params.position': 'Posição do Nível',
        'analysis.params.sweep': 'Varredura',
        'analysis.params.width': 'Largura',
        'analysis.params.opacity': 'Opacidade',
        'analysis.params.normalize': 'Normalizar',
        'analysis.params.intensity': 'Intensidade',
        'analysis.params.minSimilarity': 'Similaridade Mínima',
        'analysis.params.minDetail': 'Detalhe Mínimo',
        'analysis.params.minClusterSize': 'Tamanho Mínimo do Cluster',
        'analysis.params.blockSize': 'Tamanho do Bloco',
        'analysis.params.showQuantized': 'Mostrar Quantizado',
        'analysis.params.maxImageSize': 'Tamanho Máximo da Imagem',
        'analysis.params.enhancement': 'Modo de Aprimoramento',
        'analysis.params.noEnhancement': 'Sem Aprimoramento',
        'analysis.params.histogramEqualization': 'Equalização de Histograma',
        'analysis.params.autoContrast': 'Contraste Automático',
        'analysis.params.autoContrastChannel': 'Contraste Automático (Por Canal)',

        // Provenance Analysis Page
        'sidebar.provenance': 'Proveniência',
        'provenance.title': 'Análise de Proveniência',
        'provenance.subtitle': 'Detecte e visualize reutilização de conteúdo entre suas imagens',
        'provenance.selectQuery': 'Selecione a Imagem de Consulta',
        'provenance.selectQueryDesc': 'Escolha a imagem para buscar reutilização de conteúdo',
        'provenance.parameters': 'Parâmetros de Análise',
        'provenance.parametersDesc': 'Configure os parâmetros para refinar a análise',
        'provenance.topK': 'Top-K (Candidatos CBIR)',
        'provenance.topKDesc': 'Número de candidatos da busca por similaridade (1-100)',
        'provenance.topQ': 'Top-Q (Expansão)',
        'provenance.topQDesc': 'Candidatos para expansão em cada correspondência (1-50)',
        'provenance.maxDepth': 'Profundidade Máxima',
        'provenance.maxDepthDesc': 'Quantos níveis expandir no grafo (1-5)',
        'provenance.descriptorType': 'Tipo de Descritor',
        'provenance.descriptorDesc': 'Algoritmo para extração de características',
        'provenance.analyze': 'Analisar Proveniência',
        'provenance.analyzing': 'Analisando...',
        'provenance.results': 'Resultados da Análise',
        'provenance.graph': 'Grafo de Proveniência',
        'provenance.noResults': 'Nenhuma correspondência encontrada',
        'provenance.noResultsDesc': 'Tente ajustar os parâmetros ou verificar se há imagens suficientes na galeria.',
        'provenance.queryImage': 'Imagem de Consulta',
        'provenance.sharedArea': 'Área Compartilhada',
        'provenance.keypoints': 'Pontos-chave',
        'provenance.matchedPairs': 'Pares Correspondentes',
        'provenance.serviceUnavailable': 'Serviço de Proveniência não disponível',
        'provenance.pending': 'Aguardando...',
        'provenance.processing': 'Processando...',
        'provenance.completed': 'Concluído',
        'provenance.failed': 'Falhou',
        'provenance.nodes': 'nós',
        'provenance.edges': 'arestas',
        'provenance.selectImageFirst': 'Selecione uma imagem primeiro.',
        'provenance.imageDetails': 'Detalhes da Imagem',
        'provenance.filename': 'Nome do Arquivo',
        'provenance.imageId': 'ID da Imagem',
        'provenance.referenceImage': 'Imagem de Referência',
        'provenance.noPreview': 'Sem Prévia',
        'provenance.filterGallery': 'Filtrar Galeria',
        'provenance.filterGalleryDesc': 'Selecione quais imagens incluir na análise (opcional)',
        'provenance.filterAll': 'Todas',
        'provenance.filterAllDesc': 'Todas as imagens da galeria serão consideradas na análise.',
        'provenance.filterByTag': 'Por Tag',
        'provenance.filterTagsDesc': 'Apenas imagens com as tags selecionadas serão incluídas.',
        'provenance.filterByDate': 'Por Data',
        'provenance.filterDateDesc': 'Apenas imagens dentro do período selecionado serão incluídas.',
        'provenance.filterManual': 'Seleção Manual',
        'provenance.filterManualDesc': 'Clique nas imagens para selecionar/deselecionar.',
        'provenance.imagesSelected': 'imagens selecionadas',
        'provenance.imagesAvailable': 'imagens disponíveis',
        'provenance.selectAllFiltered': 'Selecionar Todas Filtradas',
        'provenance.selectPage': 'Selec. Página',
        'provenance.selectAllOnPage': 'Selecionar Página',
        'provenance.selectAllWithTags': 'Selecionar Todas com Tags',
        'provenance.clearPageSelection': 'Limpar Página',
        'provenance.clearTagSelection': 'Limpar Seleção de Tags',
        'provenance.imagesSelected': 'imagens selecionadas',
        'provenance.queryImageSuggestions': 'Sugestões da imagem de consulta:',
        'provenance.searchByFilename': 'Buscar por nome do arquivo',
        'provenance.filterBySimilarity': 'Por Similaridade',
        'provenance.filterSimilarityDesc': 'Buscar imagens semelhantes à imagem de consulta usando CBIR.',
        'provenance.findSimilar': 'Buscar Similares',
        'provenance.selectQueryFirst': 'Selecione uma imagem de consulta primeiro.',
        'provenance.similarityNotSearched': 'Nenhuma busca de similaridade foi realizada ainda',
        'provenance.similarityNotSearchedHint': 'Clique em "Buscar Similares" acima para encontrar imagens semelhantes à sua consulta.',
        'provenance.queryLabel': 'Consulta:',
        'provenance.foundSimilarImages': 'Encontradas {{count}} imagens similares',
        'provenance.allImagesPrefix': 'Todas as',
        'provenance.allImagesSuffix': 'imagens da galeria serão consideradas na análise',

        // Copy-Move Detection
        'sidebar.copyMove': 'Detecção Copy-Move',
        'copyMove.title': 'Detecção Copy-Move',
        'copyMove.subtitle': 'Detecte regiões duplicadas dentro ou entre imagens',
        'copyMove.mode': 'Modo de Detecção',
        'copyMove.singleMode': 'Imagem Única',
        'copyMove.crossMode': 'Imagens Cruzadas',
        'copyMove.selectImage': 'Selecione uma Imagem',
        'copyMove.selectSource': 'Selecione a Imagem de Origem',
        'copyMove.selectTarget': 'Selecione a Imagem de Destino',
        'copyMove.selectedImages': 'Imagens Selecionadas',
        'copyMove.source': 'Origem',
        'copyMove.target': 'Destino',
        'copyMove.notSelected': 'Não selecionada',
        'copyMove.method': 'Método de Detecção',
        'copyMove.methodDesc': 'Selecione o tipo de algoritmo',
        'copyMove.keypointDesc': 'Detecção avançada baseada em pontos-chave (SIFT/RootSIFT). Recomendado para imagens cruzadas.',
        'copyMove.keypointCrossOnly': 'Método Keypoint disponível apenas para detecção de imagens cruzadas',
        'copyMove.denseDesc': 'Correspondência densa baseada em blocos. Melhor para detecção de cópia-mover intensa.',
        'copyMove.denseVariant': 'Variante do Método Denso',
        'copyMove.descriptorType': 'Tipo de Descritor',
        'copyMove.descriptorRsift': 'RootSIFT - Variante normalizada do SIFT (recomendado)',
        'copyMove.descriptorSift': 'SIFT - Padrão Scale-Invariant Feature Transform',
        'copyMove.descriptorVlfeat': 'VLFeat SIFT HEQ - SIFT com equalização de histograma',
        'copyMove.analyze': 'Executar Análise',
        'copyMove.analyzing': 'Analisando...',
        'copyMove.analysisStarted': 'Análise iniciada',
        'copyMove.results': 'Resultados',
        'copyMove.matches': 'Correspondências',
        'copyMove.clusters': 'Clusters',
        'copyMove.noResults': 'Nenhuma região duplicada encontrada',
        'copyMove.pending': 'Aguardando...',
        'copyMove.processing': 'Processando...',
        'copyMove.completed': 'Análise concluída!',
        'copyMove.failed': 'Análise falhou',
        'copyMove.timeout': 'Tempo limite excedido',
        'copyMove.selectImageFirst': 'Selecione uma imagem primeiro',
        'copyMove.selectBothImages': 'Selecione ambas as imagens',
        'copyMove.selectAndRun': 'Selecione uma imagem e execute a análise para ver os resultados',
        'copyMove.noImages': 'Nenhuma imagem disponível',
        'copyMove.singleModeDesc': 'Detecte regiões duplicadas dentro de uma única imagem',
        'copyMove.crossModeDesc': 'Compare duas imagens para encontrar conteúdo compartilhado',
        'copyMove.advancedOptions': 'Opções Avançadas',
        'copyMove.startOver': 'Recomeçar',
        'copyMove.newAnalysis': 'Nova Análise',
        'copyMove.analysisInProgress': 'Isso pode levar alguns segundos...',
        'copyMove.failedDesc': 'Ocorreu um erro durante a análise. Por favor, tente novamente.',
        'copyMove.noResultsDesc': 'A análise não encontrou regiões duplicadas nesta imagem.',
        'copyMove.downloadMatches': 'Baixar Correspondências',
        'copyMove.downloadClusters': 'Baixar Clusters',
        'copyMove.downloadError': 'Erro ao baixar resultados',
        'copyMove.loadingResults': 'Carregando resultados...',
        'copyMove.noMatchesImage': 'Nenhuma imagem de correspondências disponível',
        'copyMove.noClustersImage': 'Nenhuma imagem de clusters disponível',
        'copyMove.selectInstructionsSingle': 'Clique em uma imagem abaixo para selecioná-la para análise.',
        'copyMove.selectInstructionsCross': 'Clique para selecionar uma imagem de origem (azul), depois clique em outra para selecionar o destino (âmbar).',
        'copyMove.step.mode': 'Modo',
        'copyMove.step.select': 'Selecionar',
        'copyMove.step.configure': 'Configurar',
        'copyMove.step.results': 'Resultados',
        'copyMove.step.modeTitle': 'Escolha o Modo de Detecção',
        'copyMove.step.modeDesc': 'Selecione se deseja analisar uma única imagem ou comparar duas imagens',
        'copyMove.step.configureTitle': 'Configure a Análise',
        'copyMove.step.configureDesc': 'Revise suas seleções e ajuste o método de detecção',
        'copyMove.step.resultsDesc': 'Veja as regiões duplicadas detectadas em suas imagens',
        'copyMove.guideTitle': 'Como Funciona a Detecção Copy-Move',
        'copyMove.guideStep1Title': 'Escolha seu modo',
        'copyMove.guideStep1Desc': 'Análise de imagem única ou comparação entre imagens',
        'copyMove.guideStep2Title': 'Selecione as imagens',
        'copyMove.guideStep2Desc': 'Escolha as imagens que deseja analisar',
        'copyMove.guideStep3Title': 'Execute a análise',
        'copyMove.guideStep3Desc': 'Configure as opções e clique em analisar',
        'copyMove.guideFooter': 'Os resultados aparecerão aqui mostrando as regiões duplicadas',
        'copyMove.summary': 'Resumo',
        'copyMove.noSimilarFound': 'Nenhuma imagem similar encontrada',
        'copyMove.selectSourceForSimilar': 'Selecione uma imagem de origem primeiro',
        'common.reset': 'Limpar',
        'common.next': 'Próximo',

        // Manipulation Detection (TruFor)
        'sidebar.manipulationDetection': 'Detecção de Manipulação',
        'manipulation.title': 'Detecção de Manipulação',
        'manipulation.subtitle': 'Detecte regiões manipuladas ou falsificadas em imagens usando aprendizado profundo',
        'manipulation.aboutTitle': 'Sobre o TruFor',
        'manipulation.aboutDescription': 'TruFor usa redes neurais avançadas para detectar e localizar falsificações em imagens, combinando características RGB de alto nível com o Noiseprint++ (impressão digital de baixo nível) para identificar anomalias.',
        'manipulation.options': 'Opções',
        'manipulation.saveNoiseprint': 'Salvar Noiseprint++',
        'manipulation.saveNoiseprintDesc': 'Salvar a saída do Noiseprint++ para análise avançada',
        'manipulation.selectedImage': 'Imagem Selecionada',
        'manipulation.image': 'Imagem',
        'manipulation.selected': 'Selecionada',
        'manipulation.notSelected': 'Não selecionada',
        'manipulation.selectImage': 'Selecione uma Imagem',
        'manipulation.selectImageFirst': 'Selecione uma imagem primeiro',
        'manipulation.analyze': 'Executar Análise',
        'manipulation.analyzing': 'Analisando...',
        'manipulation.analysisStarted': 'Análise iniciada',
        'manipulation.results': 'Resultados',
        'manipulation.integrityScore': 'Pontuação de Integridade',
        'manipulation.highRisk': 'Alto risco de manipulação detectado',
        'manipulation.mediumRisk': 'Possível manipulação detectada',
        'manipulation.lowRisk': 'Imagem aparenta ser autêntica',
        'manipulation.noResults': 'Análise concluída sem resultados de visualização',
        'manipulation.pending': 'Aguardando...',
        'manipulation.processing': 'Processando...',
        'manipulation.completed': 'Análise concluída!',
        'manipulation.failed': 'Análise falhou',
        'manipulation.timeout': 'Tempo limite excedido',
        'manipulation.downloadError': 'Erro ao baixar resultados',
        'manipulation.loadingResults': 'Carregando resultados...',
        'manipulation.noVisualization': 'Nenhuma visualização disponível',
        'manipulation.downloadResult': 'Baixar Resultado',
        'manipulation.selectAndRun': 'Selecione uma imagem e execute a análise para ver o mapa de manipulações',
        'manipulation.noImages': 'Nenhuma imagem disponível',

        // API Error Messages
        'api.sessionExpired': 'Sessão expirada ou inválida. Por favor, faça login novamente.',
        'api.requestError': 'Ocorreu um erro na requisição.',
        'api.downloadError': 'Falha no download do arquivo.',
    },
    en: {
        // Auth Page
        'auth.welcome': 'Welcome back!',
        'auth.createAccount': 'Create your account',
        'auth.platformAccess': 'ELIS Scientific Integrity Platform',
        'auth.username': 'Username',
        'auth.usernamePlaceholder': 'your_username',
        'auth.fullName': 'Full Name',
        'auth.fullNamePlaceholder': 'John Doe',
        'auth.usernameOrEmail': 'Username or Email',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'your@email.com',
        'auth.password': 'Password',
        'auth.passwordPlaceholder': '••••••••',
        'auth.login': 'Sign In',
        'auth.register': 'Create Account',
        'auth.loading': 'Loading...',
        'auth.noAccount': "Don't have an account?",
        'auth.hasAccount': 'Already have an account?',
        'auth.signupHere': 'Sign up here',
        'auth.loginHere': 'Log in',
        'auth.copyright': '© 2024 ELIS Platform. All rights reserved.',

        // Sidebar
        'sidebar.platform': 'Scientific Integrity',
        'sidebar.researcher': 'Researcher',
        'sidebar.search': 'Search...',
        'sidebar.images': 'Images',
        'sidebar.uploadImages': 'Upload Images',
        'sidebar.gallery': 'Gallery',
        'sidebar.annotate': 'Annotate Images',
        'sidebar.documents': 'Documents',
        'sidebar.viewPdfs': 'View PDFs',
        'sidebar.uploadPdf': 'Upload PDF',
        'sidebar.tools': 'Tools',
        'sidebar.findSimilar': 'Find Similar',
        'sidebar.imageAnalysis': 'Image Analysis',
        'sidebar.tags': 'Tags',
        'sidebar.categories': 'Categories',
        'sidebar.settings': 'Settings',
        'sidebar.general': 'General',
        'sidebar.profile': 'Profile',
        'sidebar.comingSoon': 'Coming soon',
        'sidebar.online': 'Online',

        // Topbar
        'topbar.title': 'ELIS Scientific Integrity',
        'topbar.subtitle': 'Advanced tools for scientific image analysis',

        // Common
        'common.loading': 'Loading...',
        'common.pleaseWait': 'Please wait...',
        'common.user': 'User',
        'common.logout': 'Logout',
        'common.searchPage': 'Search Page (Coming Soon)',
        'common.cancel': 'Cancel',
        'common.save': 'Save',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.confirm': 'Confirm',
        'common.success': 'Success!',
        'common.error': 'Error',
        'common.warning': 'Warning',
        'common.tryAgain': 'Try Again',
        'common.addMore': 'Add more',
        'common.filters': 'Filters',
        'common.active': 'Active',
        'common.all': 'All',
        'common.origin': 'Source',
        'common.update': 'Update',
        'common.back': 'Back',
        'common.selected': 'selected',

        // Upload Pages
        'upload.title': 'Upload Images',
        'upload.subtitle': 'Add images for analysis and processing',
        'upload.pdfTitle': 'Upload PDF',
        'upload.pdfSubtitle': 'Add PDF documents for extraction and analysis',
        'upload.dragDropImages': 'Drag and drop your images here',
        'upload.dragDropPdfs': 'Drag and drop your PDFs here',
        'upload.orClick': 'or click to select from computer',
        'upload.supportsImages': 'Supports: JPG, PNG, GIF, WEBP',
        'upload.supportsPdf': 'Supports: PDF',
        'upload.selectedFiles': 'Selected Files',
        'upload.completeUpload': 'Complete Upload',
        'upload.selectAtLeastOneImage': 'Please select at least one image.',
        'upload.selectAtLeastOnePdf': 'Please select at least one PDF.',
        'upload.uploadSuccess': 'Upload completed successfully!',
        'upload.uploadPartial': 'Upload partially completed.',
        'upload.uploadFailed': 'Upload failed. Please try again.',
        'upload.imagesUploaded': 'image(s) uploaded successfully!',
        'upload.pdfsUploaded': 'PDF(s) uploaded successfully!',
        'upload.successCount': 'success(es)',
        'upload.failureCount': 'failure(s)',

        // Gallery
        'gallery.title': 'Gallery',
        'gallery.subtitle': 'Manage, organize, and analyze your extracted and uploaded images.',
        'gallery.empty': 'Empty gallery',
        'gallery.noResults': 'No results found',
        'gallery.emptyDescription': 'Start by uploading some images for analysis or extracting from PDFs.',
        'gallery.noResultsDescription': 'Try adjusting your filters or search for other terms.',
        'gallery.upload': 'Upload',
        'gallery.noTags': 'No tags',
        'gallery.uploaded': 'Uploaded',
        'gallery.extracted': 'Extracted',
        'gallery.searchPlaceholder': 'Search images...',
        'gallery.sortNewest': 'Newest first',
        'gallery.sortOldest': 'Oldest first',
        'gallery.sortNameAsc': 'Name (A-Z)',
        'gallery.sortNameDesc': 'Name (Z-A)',
        'gallery.sortSize': 'Size',
        'gallery.errorLoading': 'Error loading images',
        'gallery.imagesTotal': 'images total',
        'gallery.selectAllImages': 'Select All',
        'gallery.selectAllFiltered': 'Select All Filtered',
        'gallery.clearAllSelection': 'Clear All',
        'gallery.images': 'images',
        'gallery.first': 'First',
        'gallery.last': 'Last',
        'gallery.previousPage': 'Previous page',
        'gallery.nextPage': 'Next page',

        // Image Filters Panel
        'filters.title': 'Filters',
        'filters.origin': 'Source',
        'filters.originAll': 'All',
        'filters.originUploaded': 'Uploaded by Me',
        'filters.originExtracted': 'Extracted from PDF',
        'filters.date': 'Date',
        'filters.dateFrom': 'From',
        'filters.dateTo': 'To',
        'filters.tags': 'Tags',
        'filters.clearFilters': 'Clear Filters',
        'filters.noTagsAvailable': 'No tags found in images',

        // Lightbox Modal
        'lightbox.tagsClassification': 'Tags & Classification',
        'lightbox.metadata': 'Metadata',
        'lightbox.origin': 'Source',
        'lightbox.format': 'Format',

        // Selection Toolbar
        'selection.selected': 'selected',
        'selection.selectedPlural': 'selected',
        'selection.clearSelection': 'Clear selection',
        'selection.findSimilar': 'Find Similar',
        'selection.findSimilarTitle': 'Find similar images',
        'selection.viewMetadata': 'Metadata',
        'selection.viewMetadataTitle': 'View image details',
        'selection.classify': 'Classify',
        'selection.analyze': 'Analyze',
        'selection.delete': 'Delete',
        'selection.extractPanels': 'Extract Panels',
        'selection.extractPanelsTitle': 'Extract individual panels from selected images',
        'selection.extracting': 'Extracting...',

        // Panel Extraction
        'panelExtraction.started': 'Panel extraction started',
        'panelExtraction.processing': 'Processing images...',
        'panelExtraction.success': 'Successfully extracted {count} panels',
        'panelExtraction.failed': 'Panel extraction failed',
        'panelExtraction.noPanelsFound': 'No panels found in the selected images',
        'panelExtraction.timeout': 'Panel extraction timed out',
        'panelExtraction.noImagesSelected': 'No images selected for extraction',

        // Batch Operations
        'batch.imagesDeleted': 'images deleted successfully.',
        'batch.extractedIgnored': 'extracted images were ignored.',
        'batch.tagsAdded': 'tags added to',
        'batch.images': 'images.',
        'batch.analyzeComingSoon': 'Batch analysis feature coming soon!',
        'batch.actionBlocked': 'Action Blocked',
        'batch.extractedOnlyMessage': 'You selected {count} extracted image(s). They can only be removed by deleting the original PDF.',
        'batch.confirmDelete': 'Are you sure you want to delete {count} images?',
        'batch.confirmDeleteNote': '(Note: {count} selected extracted images will be ignored and not deleted)',
        'batch.confirmation': 'Confirmation',

        // Tag Input
        'tags.addTags': 'Add tags...',

        // Image display
        'image.error': 'Error',
        'image.loadError': 'Error loading image',
        'image.noTags': 'No tags',
        'image.uploaded': 'Uploaded',
        'image.extracted': 'Extracted',
        'image.noName': 'No name',

        // Image operations (useImages hook)
        'images.actionBlocked': 'Action Blocked',
        'images.extractedCannotDelete': 'Extracted images cannot be deleted individually. To remove this image, you must delete the original PDF in the "Documents" tab.',
        'images.confirmDeleteTitle': 'Are you sure?',
        'images.confirmDeleteMessage': 'Do you really want to delete the image "{filename}"?',
        'images.deleteSuccess': 'Image deleted successfully!',
        'images.deleteError': 'Error deleting',
        'images.tagsAddedSuccess': 'Tags added successfully!',
        'images.tagsAddError': 'Error adding tags',
        'images.tagRemovedSuccess': 'Tag removed successfully.',
        'images.tagRemoveError': 'Error removing tag',

        // Similarity Search
        'similarity.title': 'Similarity Search',
        'similarity.searching': 'Searching...',
        'similarity.resultsFound': 'results found',
        'similarity.topK': 'Top-K',
        'similarity.threshold': 'Threshold',
        'similarity.category': 'Category',
        'similarity.selectAllResults': 'Select All Results',
        'similarity.noResults': 'No similar images found.',
        'similarity.foundResults': 'similar images found!',
        'similarity.found': 'Found',
        'similarity.similarImages': 'similar images!',
        'similarity.searchError': 'Search Error',
        'similarity.searchErrorMessage': 'Error searching for similar images.',
        'similarity.selectOneImage': 'Select exactly one image to search for similar ones.',

        // Batch Tag Modal
        'batchTag.title': 'Classify Images',
        'batchTag.description': 'Add tags to classify the',
        'batchTag.selectedImages': 'selected images',
        'batchTag.addToExisting': 'They will be added to existing tags.',
        'batchTag.newTags': 'New Tags',
        'batchTag.addTags': 'Add Tags',

        // Profile Page
        'profile.title': 'My Profile',
        'profile.subtitle': 'Manage your personal information and settings',
        'profile.fullName': 'Full Name',
        'profile.fullNamePlaceholder': 'Your full name',
        'profile.email': 'Email',
        'profile.editProfile': 'Edit Profile',
        'profile.saveChanges': 'Save Changes',
        'profile.saving': 'Saving...',
        'profile.storage': 'Storage',
        'profile.used': 'used',
        'profile.total': 'total',
        'profile.spaceUsed': 'of space used',
        'profile.accountInfo': 'Account Information',
        'profile.createdAt': 'Created at',
        'profile.lastUpdate': 'Last update',
        'profile.dangerZone': 'Danger Zone',
        'profile.dangerDescription': 'Account deletion is permanent and cannot be undone. All your documents will be deleted.',
        'profile.deleteAccount': 'Delete Account Permanently',
        'profile.errorLoading': 'Error loading profile',
        'profile.deleteConfirmTitle': 'WARNING: This action is IRREVERSIBLE!',
        'profile.deleteConfirmMessage': 'All your documents and data will be PERMANENTLY deleted.',
        'profile.deleteConfirmPrompt': 'Type your username to confirm:',
        'profile.deleteCancelled': 'Incorrect username. Action cancelled.',

        // View PDFs Page
        'pdfs.title': 'My Documents',
        'pdfs.subtitle': 'View and manage your PDF documents',
        'pdfs.empty': 'No PDFs uploaded',
        'pdfs.noDocFound': 'No documents found',
        'pdfs.emptyDescription': 'You haven\'t uploaded any PDF documents to the platform yet.',
        'pdfs.searchNoResults': 'Try searching with other terms or clear filters.',
        'pdfs.uploadNow': 'Upload Now',
        'pdfs.documentsFound': 'documents found',
        'pdfs.searchPlaceholder': 'Search documents...',
        'pdfs.sortNewest': 'Newest first',
        'pdfs.sortOldest': 'Oldest first',
        'pdfs.sortSize': 'Largest size',
        'pdfs.view': 'View',
        'pdfs.download': 'Download',
        'pdfs.delete': 'Delete',
        'pdfs.watermarkOptions': 'Watermark Options',
        'pdfs.removeWatermark': 'Remove Watermark',
        'pdfs.none': 'None',
        'pdfs.keepOriginal': 'Keep original',
        'pdfs.level1': 'Level 1',
        'pdfs.level1Sub': 'Light removal',
        'pdfs.level2': 'Level 2',
        'pdfs.level2Sub': 'Medium removal',
        'pdfs.level3': 'Level 3',
        'pdfs.level3Sub': 'Aggressive removal',
        'pdfs.loadingDoc': 'Loading document...',
        'pdfs.loadError': 'Could not load the document.',
        'pdfs.complete': 'Complete',
        'pdfs.processing': 'Processing',
        'pdfs.waiting': 'Waiting',
        'pdfs.grid': 'Grid',
        'pdfs.list': 'List',
        'pdfs.splitView': 'Split View',
        'pdfs.selectDocToView': 'Select a document to view',
        'pdfs.name': 'Name',
        'pdfs.date': 'Date',
        'pdfs.size': 'Size',
        'pdfs.status': 'Status',
        'pdfs.actions': 'Actions',
        'pdfs.goToUpload': 'Go to the upload page',
        'document.confirmDeleteTitle': 'Are you sure?',
        'document.confirmDeleteMessage': 'Do you really want to delete the document "{filename}"? This action cannot be undone.',
        'document.deleteSuccess': 'Document deleted successfully!',
        'document.downloadStarted': 'Download started!',
        'document.downloadError': 'Error downloading',
        'document.deleteError': 'Error deleting',
        'document.fetchError': 'Error fetching documents',

        // CBIR Search Page
        'cbir.title': 'Find Similar Images',
        'cbir.subtitle': 'Select a source image and find visually similar images in your gallery.',
        'cbir.clearSearch': 'Clear search',
        'cbir.noImages': 'No images available',
        'cbir.noImagesDescription': 'Upload images first to use similarity search.',
        'cbir.noSimilarFound': 'No similar images found',
        'cbir.noSimilarDescription': 'Try adjusting search parameters or select another source image.',
        'cbir.selectSource': 'Select Source Image',
        'cbir.selectSourceDescription': 'Choose the image to use as reference for the search',
        'cbir.searchParams': 'Search Parameters',
        'cbir.searchParamsDescription': 'Configure criteria to refine your search',
        'cbir.topK': 'Number of Results (Top-K)',
        'cbir.topKDescription': 'Maximum number of similar images to return (1-100)',
        'cbir.minSimilarity': 'Minimum Similarity',
        'cbir.minSimilarityDescription': 'Filter results below this similarity threshold',
        'cbir.categoryFilter': 'Category/Type Filter',
        'cbir.allTypes': 'All Types',
        'cbir.autoSelected': 'Auto-selected based on source image',
        'cbir.filterByType': 'Filter results by image type',
        'cbir.selectedImage': 'Selected image:',
        'cbir.noImageSelected': 'No image selected',
        'cbir.analyze': 'Analyze',
        'cbir.searching': 'Searching...',
        'cbir.searchResults': 'Search Results',
        'cbir.imagesFound': 'of',
        'cbir.imagesFoundSuffix': 'images found',
        'cbir.filteredBySimilarity': 'filtered by minimum similarity',
        'cbir.error': 'Error',
        'cbir.noTags': 'No tags',
        'cbir.similarity': 'Similarity',
        'cbir.tags': 'Tags',
        'cbir.info': 'Information',
        'cbir.origin': 'Source',
        'cbir.selectSourceFirst': 'Select a source image first.',
        'cbir.noResultsWithCriteria': 'No similar images found with current criteria.',

        // Annotation Page
        'annotation.title': 'Annotate Images',
        'annotation.subtitle': 'Add annotations and markings to your images',
        'annotation.selectImage': 'Select an image to annotate',
        'annotation.tools': 'Tools',
        'annotation.rectangle': 'Rectangle',
        'annotation.circle': 'Circle',
        'annotation.arrow': 'Arrow',
        'annotation.text': 'Text',
        'annotation.saveAnnotation': 'Save Annotation',
        'annotation.listTitle': 'Annotations',
        'annotation.placeholder': 'Type your annotation here...',
        'annotation.noAnnotations': 'No annotations yet.',
        'annotation.type': 'Type',
        'annotation.manipulation': 'Manipulation',
        'annotation.copyMove': 'Copy-Move',
        'annotation.groupId': 'Group ID',
        'annotation.group': 'Group',

        // Image Analysis Page
        'analysis.title': 'Image Analysis',
        'analysis.subtitle': 'Forensic analysis tools for scientific image integrity',
        'analysis.inspiredBy': 'Inspired by Forensically',
        'analysis.selectImage': 'Select Image',
        'analysis.selectImageDesc': 'Choose an image from your gallery to analyze',
        'analysis.selectTool': 'Select Analysis Tool',
        'analysis.selectToolDesc': 'Choose a forensics tool to analyze the image',
        'analysis.parameters': 'Parameters & Run',
        'analysis.parametersDesc': 'Adjust settings and run the analysis',
        'analysis.selectedImage': 'Selected image:',
        'analysis.noImageSelected': 'No image selected',
        'analysis.runAnalysis': 'Run Analysis',
        'analysis.analyzing': 'Analyzing...',
        'analysis.results': 'Analysis Results',
        'analysis.result': 'Result',
        'analysis.original': 'Original',
        'analysis.processing': 'Processing...',
        'analysis.complete': 'Analysis complete',
        'analysis.error': 'Error during analysis',
        'analysis.selectImageFirst': 'Please select an image first',
        'analysis.noImages': 'No images found',
        'analysis.noImagesDesc': 'Upload some images to get started with analysis.',
        'analysis.selectAndRun': 'Select an image and run analysis',
        'analysis.selectDescription': 'Choose an image from the gallery and select a tool to begin analysis.',
        'analysis.noParams': 'No adjustable parameters for this tool.',
        'analysis.fileSize': 'File Size',
        'analysis.foundStrings': 'Found',
        'analysis.strings': 'strings',
        'analysis.noStrings': 'No significant strings found',
        'analysis.tools.ela': 'Error Level Analysis',
        'analysis.tools.noise': 'Noise Analysis',
        'analysis.tools.gradient': 'Luminance Gradient',
        'analysis.tools.levelSweep': 'Level Sweep',
        'analysis.tools.magnifier': 'Magnifier',
        'analysis.tools.cloneDetection': 'Clone Detection',
        'analysis.tools.metadata': 'Metadata',
        'analysis.tools.jpegAnalysis': 'JPEG Analysis',
        'analysis.tools.strings': 'String Extraction',
        'analysis.tools.ela.description': 'Compares the image to a recompressed version to detect manipulation',
        'analysis.tools.noise.description': 'Extracts and visualizes the noise pattern of the image',
        'analysis.tools.gradient.description': 'Visualizes brightness changes to detect lighting inconsistencies',
        'analysis.tools.levelSweep.description': 'Highlights specific brightness levels to reveal hidden details',
        'analysis.tools.magnifier.description': 'Zoom and enhance image details with histogram equalization',
        'analysis.tools.cloneDetection.description': 'Identifies potentially copied and pasted regions',
        'analysis.tools.metadata.description': 'View image properties and embedded information',
        'analysis.tools.jpegAnalysis.description': 'Analyze JPEG structure and quantization tables',
        'analysis.tools.strings.description': 'Extract text strings embedded in the image file',
        'analysis.params.quality': 'JPEG Quality',
        'analysis.params.jpegQuality': 'JPEG Quality',
        'analysis.params.scale': 'Error Scale',
        'analysis.params.errorScale': 'Error Scale',
        'analysis.params.amplitude': 'Noise Amplitude',
        'analysis.params.noiseAmplitude': 'Noise Amplitude',
        'analysis.params.equalize': 'Equalize Histogram',
        'analysis.params.equalizeHistogram': 'Equalize Histogram',
        'analysis.params.position': 'Level Position',
        'analysis.params.sweep': 'Sweep',
        'analysis.params.width': 'Width',
        'analysis.params.opacity': 'Opacity',
        'analysis.params.normalize': 'Normalize',
        'analysis.params.intensity': 'Intensity',
        'analysis.params.minSimilarity': 'Min Similarity',
        'analysis.params.minDetail': 'Min Detail',
        'analysis.params.minClusterSize': 'Min Cluster Size',
        'analysis.params.blockSize': 'Block Size',
        'analysis.params.showQuantized': 'Show Quantized',
        'analysis.params.maxImageSize': 'Max Image Size',
        'analysis.params.enhancement': 'Enhancement Mode',
        'analysis.params.noEnhancement': 'No Enhancement',
        'analysis.params.histogramEqualization': 'Histogram Equalization',
        'analysis.params.autoContrast': 'Auto Contrast',
        'analysis.params.autoContrastChannel': 'Auto Contrast (Per Channel)',

        // Provenance Analysis Page
        'sidebar.provenance': 'Provenance',
        'provenance.title': 'Provenance Analysis',
        'provenance.subtitle': 'Detect and visualize content reuse among your images',
        'provenance.selectQuery': 'Select Query Image',
        'provenance.selectQueryDesc': 'Choose the image to search for content reuse',
        'provenance.parameters': 'Analysis Parameters',
        'provenance.parametersDesc': 'Configure the parameters to refine the analysis',
        'provenance.topK': 'Top-K (CBIR Candidates)',
        'provenance.topKDesc': 'Number of candidates from similarity search (1-100)',
        'provenance.topQ': 'Top-Q (Expansion)',
        'provenance.topQDesc': 'Candidates for expansion on each match (1-50)',
        'provenance.maxDepth': 'Max Depth',
        'provenance.maxDepthDesc': 'How many levels to expand the graph (1-5)',
        'provenance.descriptorType': 'Descriptor Type',
        'provenance.descriptorDesc': 'Algorithm for feature extraction',
        'provenance.analyze': 'Analyze Provenance',
        'provenance.analyzing': 'Analyzing...',
        'provenance.results': 'Analysis Results',
        'provenance.graph': 'Provenance Graph',
        'provenance.noResults': 'No matches found',
        'provenance.noResultsDesc': 'Try adjusting parameters or make sure there are enough images in the gallery.',
        'provenance.queryImage': 'Query Image',
        'provenance.sharedArea': 'Shared Area',
        'provenance.keypoints': 'Keypoints',
        'provenance.matchedPairs': 'Matched Pairs',
        'provenance.serviceUnavailable': 'Provenance Service unavailable',
        'provenance.pending': 'Pending...',
        'provenance.processing': 'Processing...',
        'provenance.completed': 'Completed',
        'provenance.failed': 'Failed',
        'provenance.nodes': 'nodes',
        'provenance.edges': 'edges',
        'provenance.selectImageFirst': 'Please select an image first.',
        'provenance.imageDetails': 'Image Details',
        'provenance.filename': 'Filename',
        'provenance.imageId': 'Image ID',
        'provenance.referenceImage': 'Reference Image',
        'provenance.noPreview': 'No Preview',
        'provenance.filterGallery': 'Filter Gallery',
        'provenance.filterGalleryDesc': 'Select which images to include in the analysis (optional)',
        'provenance.filterAll': 'All Images',
        'provenance.filterAllDesc': 'All images in the gallery will be considered in the analysis.',
        'provenance.filterByTag': 'By Tag',
        'provenance.filterTagsDesc': 'Only images with selected tags will be included.',
        'provenance.filterByDate': 'By Date',
        'provenance.filterDateDesc': 'Only images within the selected date range will be included.',
        'provenance.filterManual': 'Manual Selection',
        'provenance.filterManualDesc': 'Click images to select/deselect.',
        'provenance.imagesSelected': 'images selected',
        'provenance.imagesAvailable': 'images available',
        'provenance.selectAllFiltered': 'Select All Filtered',
        'provenance.selectPage': 'Select Page',
        'provenance.selectAllOnPage': 'Select All on Page',
        'provenance.selectAllWithTags': 'Select All with Tags',
        'provenance.clearPageSelection': 'Clear Page',
        'provenance.clearTagSelection': 'Clear Tag Selection',
        'provenance.imagesSelected': 'images selected',
        'provenance.queryImageSuggestions': 'Query image suggestions:',
        'provenance.searchByFilename': 'Search by filename',
        'provenance.filterBySimilarity': 'By Similarity',
        'provenance.filterSimilarityDesc': 'Find images similar to the query image using CBIR.',
        'provenance.findSimilar': 'Find Similar',
        'provenance.selectQueryFirst': 'Select a query image first.',
        'provenance.similarityNotSearched': 'No similarity search performed yet',
        'provenance.similarityNotSearchedHint': 'Click "Find Similar" above to find images similar to your query.',
        'provenance.queryLabel': 'Query:',
        'provenance.foundSimilarImages': 'Found {{count}} similar images',
        'provenance.allImagesPrefix': 'All',
        'provenance.allImagesSuffix': 'images from the gallery will be considered in the analysis',

        // Copy-Move Detection
        'sidebar.copyMove': 'Copy-Move Detection',
        'copyMove.title': 'Copy-Move Detection',
        'copyMove.subtitle': 'Detect duplicated regions within or across images',
        'copyMove.mode': 'Detection Mode',
        'copyMove.singleMode': 'Single Image',
        'copyMove.crossMode': 'Cross Image',
        'copyMove.selectImage': 'Select an Image',
        'copyMove.selectSource': 'Select Source Image',
        'copyMove.selectTarget': 'Select Target Image',
        'copyMove.selectedImages': 'Selected Images',
        'copyMove.source': 'Source',
        'copyMove.target': 'Target',
        'copyMove.notSelected': 'Not selected',
        'copyMove.method': 'Detection Method',
        'copyMove.methodDesc': 'Select the algorithm type',
        'copyMove.keypointDesc': 'Advanced keypoint-based detection (SIFT/RootSIFT). Recommended for cross-image detection.',
        'copyMove.keypointCrossOnly': 'Keypoint method is only available for cross-image detection',
        'copyMove.denseDesc': 'Block-based dense matching. Better for intensive copy-move detection.',
        'copyMove.denseVariant': 'Dense Method Variant',
        'copyMove.descriptorType': 'Descriptor Type',
        'copyMove.descriptorRsift': 'RootSIFT - Normalized SIFT variant (recommended)',
        'copyMove.descriptorSift': 'SIFT - Standard Scale-Invariant Feature Transform',
        'copyMove.descriptorVlfeat': 'VLFeat SIFT HEQ - SIFT with histogram equalization',
        'copyMove.analyze': 'Run Analysis',
        'copyMove.analyzing': 'Analyzing...',
        'copyMove.analysisStarted': 'Analysis started',
        'copyMove.results': 'Results',
        'copyMove.matches': 'Matches',
        'copyMove.clusters': 'Clusters',
        'copyMove.noResults': 'No duplicated regions found',
        'copyMove.pending': 'Pending...',
        'copyMove.processing': 'Processing...',
        'copyMove.completed': 'Analysis complete!',
        'copyMove.failed': 'Analysis failed',
        'copyMove.timeout': 'Analysis timed out',
        'copyMove.selectImageFirst': 'Select an image first',
        'copyMove.selectBothImages': 'Select both images',
        'copyMove.selectAndRun': 'Select an image and run analysis to see results',
        'copyMove.noImages': 'No images available',
        'copyMove.singleModeDesc': 'Detect duplicated regions within a single image',
        'copyMove.crossModeDesc': 'Compare two images to find shared content',
        'copyMove.advancedOptions': 'Advanced Options',
        'copyMove.startOver': 'Start Over',
        'copyMove.newAnalysis': 'New Analysis',
        'copyMove.analysisInProgress': 'This may take a few seconds...',
        'copyMove.failedDesc': 'An error occurred during analysis. Please try again.',
        'copyMove.noResultsDesc': 'The analysis found no duplicated regions in this image.',
        'copyMove.downloadMatches': 'Download Matches',
        'copyMove.downloadClusters': 'Download Clusters',
        'copyMove.downloadError': 'Error downloading results',
        'copyMove.loadingResults': 'Loading results...',
        'copyMove.noMatchesImage': 'No matches image available',
        'copyMove.noClustersImage': 'No clusters image available',
        'copyMove.selectInstructionsSingle': 'Click on an image below to select it for analysis.',
        'copyMove.selectInstructionsCross': 'Click to select a source image (blue), then click another to select the target (amber).',
        'copyMove.step.mode': 'Mode',
        'copyMove.step.select': 'Select',
        'copyMove.step.configure': 'Configure',
        'copyMove.step.results': 'Results',
        'copyMove.step.modeTitle': 'Choose Detection Mode',
        'copyMove.step.modeDesc': 'Select whether you want to analyze a single image or compare two images',
        'copyMove.step.configureTitle': 'Configure the Analysis',
        'copyMove.step.configureDesc': 'Review your selections and adjust the detection method',
        'copyMove.step.resultsDesc': 'View the duplicated regions detected in your images',
        'copyMove.guideTitle': 'How Copy-Move Detection Works',
        'copyMove.guideStep1Title': 'Choose your mode',
        'copyMove.guideStep1Desc': 'Single image analysis or cross-image comparison',
        'copyMove.guideStep2Title': 'Select images',
        'copyMove.guideStep2Desc': 'Choose the images you want to analyze',
        'copyMove.guideStep3Title': 'Run the analysis',
        'copyMove.guideStep3Desc': 'Configure options and click analyze',
        'copyMove.guideFooter': 'Results will appear here showing duplicated regions',
        'copyMove.summary': 'Summary',
        'copyMove.noSimilarFound': 'No similar images found',
        'copyMove.selectSourceForSimilar': 'Select a source image first',
        'common.reset': 'Reset',
        'common.next': 'Next',

        // Manipulation Detection (TruFor)
        'sidebar.manipulationDetection': 'Manipulation Detection',
        'manipulation.title': 'Manipulation Detection',
        'manipulation.subtitle': 'Detect manipulated or forged regions in images using deep learning',
        'manipulation.aboutTitle': 'About TruFor',
        'manipulation.aboutDescription': 'TruFor uses advanced neural networks to detect and localize image forgeries, combining high-level RGB features with Noiseprint++ (low-level fingerprint) to identify anomalies.',
        'manipulation.options': 'Options',
        'manipulation.saveNoiseprint': 'Save Noiseprint++',
        'manipulation.saveNoiseprintDesc': 'Save the Noiseprint++ output for advanced analysis',
        'manipulation.selectedImage': 'Selected Image',
        'manipulation.image': 'Image',
        'manipulation.selected': 'Selected',
        'manipulation.notSelected': 'Not selected',
        'manipulation.selectImage': 'Select an Image',
        'manipulation.selectImageFirst': 'Select an image first',
        'manipulation.analyze': 'Run Analysis',
        'manipulation.analyzing': 'Analyzing...',
        'manipulation.analysisStarted': 'Analysis started',
        'manipulation.results': 'Results',
        'manipulation.integrityScore': 'Integrity Score',
        'manipulation.highRisk': 'High manipulation risk detected',
        'manipulation.mediumRisk': 'Possible manipulation detected',
        'manipulation.lowRisk': 'Image appears to be authentic',
        'manipulation.noResults': 'Analysis completed without visualization results',
        'manipulation.pending': 'Pending...',
        'manipulation.processing': 'Processing...',
        'manipulation.completed': 'Analysis complete!',
        'manipulation.failed': 'Analysis failed',
        'manipulation.timeout': 'Analysis timed out',
        'manipulation.downloadError': 'Error downloading results',
        'manipulation.loadingResults': 'Loading results...',
        'manipulation.noVisualization': 'No visualization available',
        'manipulation.downloadResult': 'Download Result',
        'manipulation.selectAndRun': 'Select an image and run analysis to see the manipulation map',
        'manipulation.noImages': 'No images available',

        // API Error Messages
        'api.sessionExpired': 'Session expired or invalid. Please log in again.',
        'api.requestError': 'An error occurred with the request.',
        'api.downloadError': 'Failed to download the file.',
    }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
    // Get initial language from localStorage or default to Portuguese
    const [language, setLanguage] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem('elis-language') || 'pt';
        }
        return 'pt';
    });

    // Toggle between English and Portuguese
    const toggleLanguage = useCallback(() => {
        setLanguage(prev => {
            const newLang = prev === 'pt' ? 'en' : 'pt';
            localStorage.setItem('elis-language', newLang);
            return newLang;
        });
    }, []);

    // Set specific language
    const setLang = useCallback((lang) => {
        if (lang === 'pt' || lang === 'en') {
            setLanguage(lang);
            localStorage.setItem('elis-language', lang);
        }
    }, []);

    // Translation function
    const t = useCallback((key) => {
        return translations[language]?.[key] || translations['pt']?.[key] || key;
    }, [language]);

    // Get locale for date formatting
    const locale = language === 'pt' ? 'pt-BR' : 'en-US';

    const value = {
        language,
        toggleLanguage,
        setLanguage: setLang,
        t,
        locale,
        isPortuguese: language === 'pt',
        isEnglish: language === 'en',
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

/**
 * Standalone translation function for use outside of React components
 * (e.g., in api.js or other service files)
 * Reads the language from localStorage and returns the translated string
 * @param {string} key - The translation key
 * @returns {string} The translated string or the key if not found
 */
export const translate = (key) => {
    const language = (typeof window !== 'undefined' && localStorage.getItem('elis-language')) || 'pt';
    return translations[language]?.[key] || translations['pt']?.[key] || key;
};

export default LanguageContext;
